apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-keyvaluestore-api
  name: my-keyvaluestore-api-svc
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 30007
  selector:
    app: my-keyvaluestore-api